name: Docker Image CI

on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

env:
  THIS_REPO: "redxlus/docker-self-hosted-runner"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ACTION_RUNNER_VERSION: $(curl --silent "https://api.github.com/repos/actions/runner/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/' | cut -c 2-)
    steps:
    - uses: actions/checkout@v3
    - name: Login the Docker image
      uses: docker/login-action@v2
      with:
        username: redxlus
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build the Docker image main
      run: |
        cd ./main
        docker build . --tag $THIS_REPO:${{ env.ACTION_RUNNER_VERSION }} --tag $THIS_REPO:latest
    - name: Build the Docker image selenium-chrome
      run: |
        cd ./selenium-chrome
        docker build . --tag $THIS_REPO:${{ env.ACTION_RUNNER_VERSION }}-selenium-chrome --tag $THIS_REPO:latest-selenium-chrome
    - name: Build the Docker image selenium-chrome-mysqlclient
      run: |
        cd ./selenium-chrome-mysqlclient
        docker build . --tag $THIS_REPO:${{ env.ACTION_RUNNER_VERSION }}-selenium-chrome-mysqlclient --tag $THIS_REPO:latest-selenium-chrome-mysqlclient
    - name: Push all the Docker image
      run: docker push $THIS_REPO --all-tags
