name: Docker Image CI

on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login the Docker image
      run: docker login -u="redxlus" -p="${DOCKER_PASSWORD}"
    - name: Build the Docker image
      run: docker build . --tag redxlus/docker-self-hosted-runner:$(date +%s)
    - name: Push the Docker image
      run: docker push redxlus/docker-self-hosted-runner:$(date +%s)
